# AMI_owner: 898082745236
# AMI_name: "Deep Learning*Amazon*7*"
AMI_image_id: ami-50570f29
EC2_user: ec2-user
instance_tags:
  Name: deep_learning
exact_count: 1

# EC2_instance_type: m5.4xlarge
# spot_price: 1

EC2_instance_type: cr1.8xlarge
spot_price: 1

# EC2_instance_type: p2.xlarge
# spot_price: 1

action_type: start
