# AMI_owner: 898082745236
# AMI_name: "Deep Learning*Amazon*7*"
AMI_image_id: ami-50570f29
EC2_user: ec2-user
instance_tags:
  Name: deep_learning
exact_count: 1
EC2_instance_type: m5.2xlarge
# EC2_instance_type: m5.large
# EC2_instance_type: t2.micro
action_type: start
