- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.value.ec2_public_dns_name }}"
    port: 22
    timeout: 360
    state: started
  with_dict: "{{ hostvars }}"
  when: item.value.ec2_state == 'running'
